version: '3.7'


networks:
  rabbitmq-manage:
  be-master:
  ms-sum:
  ms-other:


volumes:
  be_master_node_modules:
    name: "be_master_node_modules"

  ms_sum_node_modules:
    name: "ms_sum_node_modules"


services:
  rabbitmq-manage:
    container_name: rabbitmq_management
    restart: unless-stopped
    image: rabbitmq:3.11-management-alpine

    networks:
      - be-master
      - ms-sum

    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  backend_master:
    container_name: backend_master
    build:
      context: ./services/be-master
      dockerfile: Dockerfile
    volumes:
      - ./services/be-master/src:/var/www/app/src


    networks:
      - be-master

    ports:
      - "3012:3000"

  micro_service_sum:
    container_name: micro_service_sum
    restart: unless-stopped

    build:
      context: ./services/ms-sum
      dockerfile: Dockerfile

    volumes:
      - ./services/ms-sum/src:/var/www/app/src

    networks:
      - ms-sum

    ports:
      - "30010:3000"
